class dofus.§\x10\x16§ extends ank.§\x1e\n\x07§.§\x1e\x15\x11§
{
   var _mcTMCC;
   static var _mcCore;
   static var _cCore;
   function §\x10\x16§(§\n\x10§)
   {
      super();
      System.security.allowDomain("*");
      fscommand("trapallkeys","true");
      dofus["\x10\x16"]._mcCore = _loc3_;
      dofus["\x10\x16"]._cCore = this;
      _global.subtrace = trace;
   }
   static function getClip()
   {
      return dofus["\x10\x16"]._mcCore;
   }
   static function getInstance()
   {
      return dofus["\x10\x16"]._cCore;
   }
   function initStart()
   {
      this.registerAllClasses();
      ank["\x1e\n\x07"]["\x0e\x1b"].addExtensions();
      this.addToQueue({object:this,method:this.addNodes});
   }
   function addNodes()
   {
      this._mcTMCC = dofus["\x10\x16"]._mcCore.createEmptyMovieClip("TemporaryMovieClipContainer",dofus["\x10\x16"]._mcCore.getNextHighestDepth());
      this._mcTMCC._visible = false;
      dofus["\x10\x16"]._mcCore.attachMovie("BATTLEFIELD","BATTLEFIELD",dofus["\x10\x16"]._mcCore.getNextHighestDepth());
      dofus["\x10\x16"]._mcCore.attachMovie("GAPIMain","GAPI",dofus["\x10\x16"]._mcCore.getNextHighestDepth());
      dofus["\x10\x16"]._mcCore.attachMovie("mask","MASK",dofus["\x10\x16"]._mcCore.getNextHighestDepth());
      this.addToQueue({object:this,method:this.initApi});
   }
   function initApi()
   {
      _global.API = new dofus["\x1e\n\x07"]["\x1d\x1b"]();
      _global.API.initialize();
      this.addToQueue({object:this,method:this.checkNodesAndContinue});
   }
   function checkNodesAndContinue()
   {
      if(this.checkNodes())
      {
         this.startGame();
      }
      else
      {
         this.addToQueue({object:this,method:this.checkNodesAndContinue});
      }
   }
   function checkNodes()
   {
      if(_global.API.gfx.initialize == undefined)
      {
         return false;
      }
      if(_global.API.kernel.start == undefined)
      {
         return false;
      }
      if(_global.API.ui.loadUIComponent == undefined)
      {
         return false;
      }
      return true;
   }
   function startGame()
   {
      _global.API.kernel.start();
   }
   function forceMouseOver()
   {
      dofus["\x10\x16"]._mcCore.attachMovie("clipForceOver","_mcForceOver",1000,{_x:dofus["\x10\x16"]._mcCore._xmouse,_y:dofus["\x10\x16"]._mcCore._ymouse});
   }
   function getTemporaryContainer()
   {
      return this._mcTMCC;
   }
   function registerAllClasses()
   {
      Object.registerClass("Loader",ank.gapi.controls.Loader);
      Object.registerClass("UI_MakeReport",dofus["\r\x14"].gapi.ui.MakeReport);
      Object.registerClass("UI_MakeMimibiote",dofus["\r\x14"].gapi.ui.MakeMimibiote);
      Object.registerClass("UI_EditPlayer",dofus["\r\x14"].gapi.ui.EditPlayer);
      Object.registerClass("Label",ank.gapi.controls.Label);
      Object.registerClass("ButtonNormalDown",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonNormalUp",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonToggleDown",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonToggleUp",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonSimpleRectangleUpDown",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("Button",ank.gapi.controls.Button);
      Object.registerClass("SpellsItem",dofus["\r\x14"].gapi.ui.spells.SpellsItem);
      Object.registerClass("BackgroundHidder",ank.gapi.controls.BackgroundHidder);
      Object.registerClass("UI_DirectionChooser",dofus["\r\x14"].gapi.ui.DirectionChooser);
      Object.registerClass("ButtonSimpleRectangleUpDown",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("UI_CardsCollectionContainerHighlight",dofus["\r\x14"].gapi.ui.inventory.ContainerHighlight);
      Object.registerClass("UI_CardsCollectionContainerBackground",dofus["\r\x14"].gapi.ui.inventory.ContainerBackground);
      Object.registerClass("ButtonMainMenuUp",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonSpellsUp",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonCraftUpInvert",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonCraftUp",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonMainMenuDown",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonSpellsDown",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonCraftDownInvert",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonCraftDown",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("TimelinePointer",dofus["\r\x14"].gapi.controls["\x1e\x0b\x03"].TimelinePointer);
      Object.registerClass("DeathCounter",dofus["\r\x14"].gapi.controls.DeathCounter);
      Object.registerClass("VerticalChrono",ank.gapi.controls.VerticalChrono);
      Object.registerClass("TimelineItem",dofus["\r\x14"].gapi.controls["\x1e\x0b\x03"].TimelineItem);
      Object.registerClass("ListInventoryViewerItemNoPrice",dofus["\r\x14"].gapi.controls["\x0b\x0f"].ListInventoryViewerItemNoPrice);
      Object.registerClass("BookPageIndexChapterItem",dofus["\r\x14"].gapi.controls["\x16\x19"].BookPageIndexChapterItem);
      Object.registerClass("MountStorageMountItem",dofus["\r\x14"].gapi.ui["\t\x1a"].MountStorageMountItem);
      Object.registerClass("ListInventoryViewerItem",dofus["\r\x14"].gapi.controls["\x0b\x0f"].ListInventoryViewerItem);
      Object.registerClass("Window",ank.gapi.controls.Window);
      Object.registerClass("ComboBoxNormal",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonComboBoxDown",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonComboBoxUp",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ComboBox",ank.gapi.controls.ComboBox);
      Object.registerClass("ListInventoryViewer",dofus["\r\x14"].gapi.controls.ListInventoryViewer);
      Object.registerClass("TextArea",ank.gapi.controls.TextArea);
      Object.registerClass("SelectableRow",ank.gapi.controls.list.SelectableRow);
      Object.registerClass("DefaultCellRenderer",ank.gapi.controls.list.DefaultCellRenderer);
      Object.registerClass("List",ank.gapi.controls.List);
      Object.registerClass("ProgressBar",ank.gapi.controls.ProgressBar);
      Object.registerClass("ItemViewer",dofus["\r\x14"].gapi.controls.ItemViewer);
      Object.registerClass("ItemViewerLite",dofus["\r\x14"].gapi.controls.ItemViewer);
      Object.registerClass("ChooseItemSkin",dofus["\r\x14"].gapi.controls.ChooseItemSkin);
      Object.registerClass("PlayerWeight",dofus["\r\x14"].gapi.controls.PlayerWeight);
      Object.registerClass("UI_PlayerShopModifier",dofus["\r\x14"].gapi.ui.PlayerShopModifier);
      Object.registerClass("UI_TaxCollectorStorage",dofus["\r\x14"].gapi.ui.TaxCollectorStorage);
      Object.registerClass("UI_PlayerShop",dofus["\r\x14"].gapi.ui.PlayerShop);
      Object.registerClass("UI_NpcShop",dofus["\r\x14"].gapi.ui.NpcShop);
      Object.registerClass("DefaultBackground",ank.gapi.controls["\x12\x10"].DefaultBackground);
      Object.registerClass("DefaultHighlight",ank.gapi.controls["\x12\x10"].DefaultHighlight);
      Object.registerClass("Container",ank.gapi.controls.Container);
      Object.registerClass("StylizedRectangle",ank.gapi.controls.StylizedRectangle);
      Object.registerClass("ContainerGrid",ank.gapi.controls.ContainerGrid);
      Object.registerClass("UI_Inventory",dofus["\r\x14"].gapi.ui.Inventory);
      Object.registerClass("UI_Inventory_DoubleFramerate",dofus["\r\x14"].gapi.ui.Inventory);
      Object.registerClass("Timeline",dofus["\r\x14"].gapi.controls.Timeline);
      Object.registerClass("UI_Timeline",dofus["\r\x14"].gapi.ui.Timeline);
      Object.registerClass("UI_ChallengeMenu",dofus["\r\x14"].gapi.ui.ChallengeMenu);
      Object.registerClass("UI_StatsJobContainerHighlight",dofus["\r\x14"].gapi.ui.inventory.ContainerHighlight);
      Object.registerClass("UI_InventoryContainerHighlight",dofus["\r\x14"].gapi.ui.inventory.ContainerHighlight);
      Object.registerClass("UI_InventoryContainerHighlight_DoubleFramerate",dofus["\r\x14"].gapi.ui.inventory.ContainerHighlight);
      Object.registerClass("UI_ForgemagusContainerHighlight",dofus["\r\x14"].gapi.ui.inventory.ContainerHighlight);
      Object.registerClass("UI_StatsJobContainerBackground2",dofus["\r\x14"].gapi.ui.inventory.ContainerBackground);
      Object.registerClass("UI_StatsJobContainerBackground",dofus["\r\x14"].gapi.ui.inventory.ContainerBackground);
      Object.registerClass("UI_InventoryContainerBackground",dofus["\r\x14"].gapi.ui.inventory.ContainerBackground);
      Object.registerClass("UI_ForgemagusContainerBackground",dofus["\r\x14"].gapi.ui.inventory.ContainerBackground);
      Object.registerClass("UI_PopupQuantity",dofus["\r\x14"].gapi.ui.PopupQuantity);
      Object.registerClass("UI_PopupHexa",dofus["\r\x14"].gapi.ui.PopupHexa);
      Object.registerClass("UI_StringCourse",dofus["\r\x14"].gapi.ui.StringCourse);
      Object.registerClass("UI_StringCourse_DoubleFramerate",dofus["\r\x14"].gapi.ui.StringCourse);
      Object.registerClass("TextInput",ank.gapi.controls.TextInput);
      Object.registerClass("ButtonTransparentUp",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("DataGrid",ank.gapi.controls.DataGrid);
      Object.registerClass("UI_Friends",dofus["\r\x14"].gapi.ui.Friends);
      Object.registerClass("UI_FightChallenge",dofus["\r\x14"].gapi.ui.FightChallenge);
      Object.registerClass("FightChallengeIcon",dofus["\r\x14"].gapi.controls.FightChallengeIcon);
      Object.registerClass("FightChallengeViewer",dofus["\r\x14"].gapi.controls.FightChallengeViewer);
      Object.registerClass("UI_SecureCraft",dofus["\r\x14"].gapi.ui.SecureCraft);
      Object.registerClass("UI_Craft",dofus["\r\x14"].gapi.ui.Craft);
      Object.registerClass("UI_Exchange",dofus["\r\x14"].gapi.ui.Exchange);
      Object.registerClass("UI_AskPrivateChat",dofus["\r\x14"].gapi.ui.AskPrivateChat);
      Object.registerClass("UI_CenterText",dofus["\r\x14"].gapi.ui.CenterText);
      Object.registerClass("UI_CenterInfo",dofus["\r\x14"].gapi.ui.CenterInfo);
      Object.registerClass("UI_AskCancel",dofus["\r\x14"].gapi.ui.AskCancel);
      Object.registerClass("UI_AskLinkWarning",dofus["\r\x14"].gapi.ui.AskLinkWarning);
      Object.registerClass("UI_AskGameBegin",dofus["\r\x14"].gapi.ui.AskGameBegin);
      Object.registerClass("UI_AskGameBegin_DoubleFramerate",dofus["\r\x14"].gapi.ui.AskGameBegin);
      Object.registerClass("UI_AskYesNo",dofus["\r\x14"].gapi.ui.AskYesNo);
      Object.registerClass("UI_AskYesNoIgnore",dofus["\r\x14"].gapi.ui.AskYesNoIgnore);
      Object.registerClass("UI_AskCustomShortcut",dofus["\r\x14"].gapi.ui.AskCustomShortcut);
      Object.registerClass("UI_ChooseNickName",dofus["\r\x14"].gapi.ui.ChooseNickName);
      Object.registerClass("UI_AskSecretAnswer",dofus["\r\x14"].gapi.ui.AskSecretAnswer);
      Object.registerClass("UI_AskAlertServer",dofus["\r\x14"].gapi.ui.AskAlertServer);
      Object.registerClass("UI_AskOk",dofus["\r\x14"].gapi.ui.AskOk);
      Object.registerClass("UI_AskOkWait",dofus["\r\x14"].gapi.ui.AskOkWait);
      Object.registerClass("UI_Login",dofus["\r\x14"].gapi.ui.Login);
      Object.registerClass("UI_Login_DoubleFramerate",dofus["\r\x14"].gapi.ui.Login);
      Object.registerClass("UI_GameOver",dofus["\r\x14"].gapi.ui.GameOver);
      Object.registerClass("UI_ItemViewer",dofus["\r\x14"].gapi.ui.ItemViewer);
      Object.registerClass("UI_ChooseItemSkin",dofus["\r\x14"].gapi.ui.ChooseItemSkin);
      Object.registerClass("MountViewer",dofus["\r\x14"].gapi.controls.MountViewer);
      Object.registerClass("UI_MountViewer",dofus["\r\x14"].gapi.ui.MountViewer);
      Object.registerClass("UI_Mount",dofus["\r\x14"].gapi.ui.Mount);
      Object.registerClass("UI_StatsJob",dofus["\r\x14"].gapi.ui.StatsJob);
      Object.registerClass("AlignmentViewer",dofus["\r\x14"].gapi.controls.AlignmentViewer);
      Object.registerClass("JobViewer",dofus["\r\x14"].gapi.controls.JobViewer);
      Object.registerClass("StatsViewer",dofus["\r\x14"].gapi.controls.StatsViewer);
      Object.registerClass("VolumeSlider",ank.gapi.controls.VolumeSlider);
      Object.registerClass("JobOptionsViewer",dofus["\r\x14"].gapi.controls.JobOptionsViewer);
      Object.registerClass("CraftViewer",dofus["\r\x14"].gapi.controls.CraftViewer);
      Object.registerClass("QuestionViewerAnswerItem",dofus["\r\x14"].gapi.controls["\x1e\x15\x18"].QuestionViewerAnswerItem);
      Object.registerClass("GuildBoostsViewerSpell",dofus["\r\x14"].gapi.controls["\r\x11"].GuildBoostsViewerSpell);
      Object.registerClass("TaxCollectorsViewerItem",dofus["\r\x14"].gapi.controls["\x1e\x0b\f"].TaxCollectorsViewerItem);
      Object.registerClass("AlignmentViewerTreeItem",dofus["\r\x14"].gapi.controls["\x1e\x0b"].AlignmentViewerTreeItem);
      Object.registerClass("ChooseServerListItem",dofus["\r\x14"].gapi.ui["\x12\x1a"].ChooseServerListItem);
      Object.registerClass("UI_JoinFriend",dofus["\r\x14"].gapi.ui.JoinFriend);
      Object.registerClass("UI_JoinFriend_DoubleFramerate",dofus["\r\x14"].gapi.ui.JoinFriend);
      Object.registerClass("CraferListItem",dofus["\r\x14"].gapi.ui["\x11\x1d"]["\x11\x1c"]);
      Object.registerClass("MountParksViewerItem",dofus["\r\x14"].gapi.controls["\r\r"].MountParksViewerItem);
      Object.registerClass("GuildMembersViewerMember",dofus["\r\x14"].gapi.controls["\r\x0e"].GuildMembersViewerMember);
      Object.registerClass("UI_GameResultPlayer",dofus["\r\x14"].gapi.ui["\r\x1c"]["\r\x1b"]);
      Object.registerClass("UI_GameResultPlayerPVP",dofus["\r\x14"].gapi.ui["\r\x1c"].GameResultPlayerPVP);
      Object.registerClass("CraftViewerCraftItem",dofus["\r\x14"].gapi.controls["\x11\x1a"].CraftViewerCraftItem);
      Object.registerClass("JobViewerSkillItem",dofus["\r\x14"].gapi.controls["\f\x06"].JobViewerSkillItem);
      Object.registerClass("StatsViewerStatItem",dofus["\r\x14"].gapi.controls["\x1e\f\x17"].StatsViewerStatItem);
      Object.registerClass("UI_NpcDialog",dofus["\r\x14"].gapi.ui.NpcDialog);
      Object.registerClass("UI_GameResult",dofus["\r\x14"].gapi.ui.GameResult);
      Object.registerClass("QuestionViewer",dofus["\r\x14"].gapi.controls.QuestionViewer);
      Object.registerClass("UI_GameResultTeamPVP",dofus["\r\x14"].gapi.ui["\r\x1c"]["\r\x1a"]);
      Object.registerClass("UI_GameResultTeam",dofus["\r\x14"].gapi.ui["\r\x1c"].GameResultTeam);
      Object.registerClass("UI_FriendsDisconnectedItem",dofus["\r\x14"].gapi.ui["\x0e\x03"]["\x0e\x01"]);
      Object.registerClass("UI_QuestsStepRewardItem",dofus["\r\x14"].gapi.ui.quests["\x1e\x15\x13"]);
      Object.registerClass("UI_BigStorePriceItem",dofus["\r\x14"].gapi.ui.bigstore["\x18\x1d"]);
      Object.registerClass("UI_FriendsConnectedItem",dofus["\r\x14"].gapi.ui["\x0e\x03"]["\x0e\x02"]);
      Object.registerClass("UI_KeyCode",dofus["\r\x14"].gapi.ui.KeyCode);
      Object.registerClass("UI_HouseIndoor",dofus["\r\x14"].gapi.ui.HouseIndoor);
      Object.registerClass("UI_ItemUtility",dofus["\r\x14"].gapi.ui.ItemUtility);
      Object.registerClass("MountWeight",dofus["\r\x14"].gapi.controls.MountWeight);
      Object.registerClass("GridInventoryViewer",dofus["\r\x14"].gapi.controls.GridInventoryViewer);
      Object.registerClass("UI_Storage",dofus["\r\x14"].gapi.ui.Storage);
      Object.registerClass("UI_Zoom",dofus["\r\x14"].gapi.ui.Zoom);
      Object.registerClass("UI_Tutorial",dofus["\r\x14"].gapi.ui.Tutorial);
      Object.registerClass("UI_MainMenu",dofus["\r\x14"].gapi.ui.MainMenu);
      Object.registerClass("UI_Register",dofus["\r\x14"].gapi.ui.Register);
      Object.registerClass("UI_Options",dofus["\r\x14"].gapi.ui.Options);
      Object.registerClass("UI_AskMainMenu",dofus["\r\x14"].gapi.ui.AskMainMenu);
      Object.registerClass("UI_MountAncestorsViewer",dofus["\r\x14"].gapi.ui.MountAncestorsViewer);
      Object.registerClass("ItemSetViewer",dofus["\r\x14"].gapi.controls.ItemSetViewer);
      Object.registerClass("LivingItemsViewer",dofus["\r\x14"].gapi.controls.LivingItemsViewer);
      Object.registerClass("SpellFullInfosViewerItem",dofus["\r\x14"].gapi.controls["\x1e\x0e\x19"].SpellFullInfosViewerItem);
      Object.registerClass("ItemViewerItem",dofus["\r\x14"].gapi.controls["\f\b"].ItemViewerItem);
      Object.registerClass("ButtonMuteSoundsDown",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonMuteMusicDown",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonMuteSoundsUp",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonMuteMusicUp",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("UI_FightOptionButtons",dofus["\r\x14"].gapi.ui.FightOptionButtons);
      Object.registerClass("ChatArea",ank.gapi.controls.ChatArea);
      Object.registerClass("Smileys",dofus["\r\x14"].gapi.controls.Smileys);
      Object.registerClass("Chat",dofus["\r\x14"].gapi.controls.Chat);
      Object.registerClass("CircleChrono",ank.gapi.controls.CircleChrono);
      Object.registerClass("ActionPointsViewer",dofus["\r\x14"].gapi.controls.PointsViewer);
      Object.registerClass("Heart",dofus["\r\x14"].gapi.controls.Heart);
      Object.registerClass("UI_Banner",dofus["\r\x14"].gapi.ui.Banner);
      Object.registerClass("ButtonBannerRoundDown",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonBannerRoundUp",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonRadioUp",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonRadioDown",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonCheckDown",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonCheckUp",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("SpellBoostViewer",dofus["\r\x14"].gapi.controls.SpellBoostViewer);
      Object.registerClass("SpellInfosViewer",dofus["\r\x14"].gapi.controls.SpellInfosViewer);
      Object.registerClass("UI_Spells",dofus["\r\x14"].gapi.ui.Spells);
      Object.registerClass("UI_MountParkSale",dofus["\r\x14"].gapi.ui.MountParkSale);
      Object.registerClass("UI_HouseSale",dofus["\r\x14"].gapi.ui.HouseSale);
      Object.registerClass("ArtworkRotationItem",dofus["\r\x14"].gapi.controls["\x1d\x0f"].ArtworkRotationItem);
      Object.registerClass("ArtworkRotation",dofus["\r\x14"].gapi.controls.ArtworkRotation);
      Object.registerClass("UI_CreateCharacter",dofus["\r\x14"].gapi.ui.CreateCharacter);
      Object.registerClass("ChooseCharacterSprite",dofus["\r\x14"].gapi.controls.ChooseCharacterSprite);
      Object.registerClass("UI_ChooseCharacter",dofus["\r\x14"].gapi.ui.ChooseCharacter);
      Object.registerClass("UI_CharactersMigration",dofus["\r\x14"].gapi.ui.CharactersMigration);
      Object.registerClass("UI_CharactersMigrationItem",dofus["\r\x14"].gapi.ui["\x12\x1d"].CharactersMigrationItem);
      Object.registerClass("UI_Gifts",dofus["\r\x14"].gapi.ui.Gifts);
      Object.registerClass("UI_ServerList",dofus["\r\x14"].gapi.ui.ServerList);
      Object.registerClass("ChooseServerSprite",dofus["\r\x14"].gapi.controls.ChooseServerSprite);
      Object.registerClass("UI_ChooseServer",dofus["\r\x14"].gapi.ui.ChooseServer);
      Object.registerClass("ButtonDecorationDown",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("UI_PlayerInfos",dofus["\r\x14"].gapi.ui.PlayerInfos);
      Object.registerClass("UI_PlayerInfosEffectsItem",dofus["\r\x14"].gapi.ui["\x1e\x16\x12"]["\x1e\x16\x11"]);
      Object.registerClass("UI_WaitingQueue",dofus["\r\x14"].gapi.ui.WaitingQueue);
      Object.registerClass("UI_WaitingMessage",dofus["\r\x14"].gapi.ui.WaitingMessage);
      Object.registerClass("UI_Waiting",dofus["\r\x14"].gapi.ui.Waiting);
      Object.registerClass("UI_Waiting_DoubleFramerate",dofus["\r\x14"].gapi.ui.Waiting);
      Object.registerClass("UI_DocumentParchment",dofus["\r\x14"].gapi.ui.DocumentParchment);
      Object.registerClass("UI_DocumentBook",dofus["\r\x14"].gapi.ui.DocumentBook);
      Object.registerClass("UI_Cinematic",dofus["\r\x14"].gapi.ui.Cinematic);
      Object.registerClass("UI_MapInfos",dofus["\r\x14"].gapi.ui.MapInfos);
      Object.registerClass("ClassInfosViewer",dofus["\r\x14"].gapi.controls.ClassInfosViewer);
      Object.registerClass("ColorPicker",ank.gapi.controls.ColorPicker);
      Object.registerClass("ClassCustomize",dofus["\r\x14"].gapi.controls.ClassCustomize);
      Object.registerClass("ButtonWomanUp",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonWomanDown",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonManDown",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonManUp",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonArrowDown",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonArrowUp",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonColorDown",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonColorUp",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonCrossDown",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonCrossUp",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonCloseDown",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonEjectDown",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonMaximizeDown",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonMinimizeDown",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonMoinsDown",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonPlusDown",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonCloseUp",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonEjectUp",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonMaximizeUp",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonMinimizeUp",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonSitUp",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonSitDown",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonMoinsUp",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonPlusUp",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("BannerSpriteInfos",dofus["\r\x14"].gapi.controls.BannerSpriteInfos);
      Object.registerClass("ButtonTabDown",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonTabUp",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonTransparentUp",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("SpouseViewer",dofus["\r\x14"].gapi.controls.SpouseViewer);
      Object.registerClass("SpellFullInfosViewer",dofus["\r\x14"].gapi.controls.SpellFullInfosViewer);
      Object.registerClass("UI_SpellInfos",dofus["\r\x14"].gapi.ui.SpellInfos);
      Object.registerClass("MapNavigator",ank.gapi.controls.MapNavigator);
      Object.registerClass("UI_MapExplorer",dofus["\r\x14"].gapi.ui.MapExplorer);
      Object.registerClass("BookPageText",dofus["\r\x14"].gapi.controls.BookPageText);
      Object.registerClass("BookPageIndex",dofus["\r\x14"].gapi.controls.BookPageIndex);
      Object.registerClass("BookPageTitle",dofus["\r\x14"].gapi.controls.BookPageTitle);
      Object.registerClass("ButtonArrowCornerDown",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonArrowCornerUp",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("Emblem",dofus["\r\x14"].gapi.controls.Emblem);
      Object.registerClass("UI_Guild",dofus["\r\x14"].gapi.ui.Guild);
      Object.registerClass("UI_CreateGuild",dofus["\r\x14"].gapi.ui.CreateGuild);
      Object.registerClass("GuildMountParkViewer",dofus["\r\x14"].gapi.controls.GuildMountParkViewer);
      Object.registerClass("TaxCollectorsViewer",dofus["\r\x14"].gapi.controls.TaxCollectorsViewer);
      Object.registerClass("GuildBoostsViewer",dofus["\r\x14"].gapi.controls.GuildBoostsViewer);
      Object.registerClass("GuildMembersViewer",dofus["\r\x14"].gapi.controls.GuildMembersViewer);
      Object.registerClass("UI_CrafterCard",dofus["\r\x14"].gapi.ui.CrafterCard);
      Object.registerClass("UI_GuildMemberInfos",dofus["\r\x14"].gapi.ui.GuildMemberInfos);
      Object.registerClass("ButtonSquareUp",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonFlatRoundLeft",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonSquareDown",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonJoinTaxCollectorDown",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonJoinTaxCollectorUp",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("TaxCollectorViewerPlayer",dofus["\r\x14"].gapi.controls["\x1e\x0b\f"]["\x1e\x0b\x0b"]);
      Object.registerClass("UI_Subway",dofus["\r\x14"].gapi.ui.Subway);
      Object.registerClass("UI_MonsterAndLookSelector",dofus["\r\x14"].gapi.ui.MonsterAndLookSelector);
      Object.registerClass("UI_ItemSelector",dofus["\r\x14"].gapi.ui.ItemSelector);
      Object.registerClass("UI_Waypoints",dofus["\r\x14"].gapi.ui.Waypoints);
      Object.registerClass("UI_ShortcutsItem",dofus["\r\x14"].gapi.ui.shortcuts["\x1e\x11\x11"]);
      Object.registerClass("UI_SubwayItem",dofus["\r\x14"].gapi.ui["\x1e\f\x03"]["\x1e\f\x02"]);
      Object.registerClass("UI_WaypointsItem",dofus["\r\x14"].gapi.ui["\x1e\t\x18"]["\x1e\t\x17"]);
      Object.registerClass("ButtonFlatRoundDown",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("UI_Buff",dofus["\r\x14"].gapi.ui.Buff);
      Object.registerClass("BuffViewer",dofus["\r\x14"].gapi.controls.BuffViewer);
      Object.registerClass("UI_BuffInfos",dofus["\r\x14"].gapi.ui.BuffInfos);
      Object.registerClass("UI_DocumentRoadSignRight",dofus["\r\x14"].gapi.ui.DocumentRoadSign);
      Object.registerClass("UI_DocumentRoadSignLeft",dofus["\r\x14"].gapi.ui.DocumentRoadSign);
      Object.registerClass("SpecializationViewer",dofus["\r\x14"].gapi.controls["\x1e\x0b"].SpecializationViewer);
      Object.registerClass("RankViewer",dofus["\r\x14"].gapi.controls["\x1e\x0b"].RankViewer);
      Object.registerClass("AlignmentViewerOrder",dofus["\r\x14"].gapi.controls["\x1e\x0b"].AlignmentViewerOrder);
      Object.registerClass("AlignmentViewerTree",dofus["\r\x14"].gapi.controls["\x1e\x0b"].AlignmentViewerTree);
      Object.registerClass("AlignmentViewerFeatsItem",dofus["\r\x14"].gapi.controls["\x1e\x0b"].AlignmentViewerFeatsItem);
      Object.registerClass("UI_FightsInfos",dofus["\r\x14"].gapi.ui.FightsInfos);
      Object.registerClass("UI_FightsInfosPlayerItem",dofus["\r\x14"].gapi.ui["\x0e\f"]["\x0e\n"]);
      Object.registerClass("UI_FightsInfosFightItem",dofus["\r\x14"].gapi.ui["\x0e\f"]["\x0e\x0b"]);
      Object.registerClass("UI_Tips",dofus["\r\x14"].gapi.ui.Tips);
      Object.registerClass("UI_CardsCollection",dofus["\r\x14"].gapi.ui.CardsCollection);
      Object.registerClass("Card",dofus["\r\x14"].gapi.controls.Card);
      Object.registerClass("UI_Indicator",dofus["\r\x14"].gapi.ui.Indicator);
      Object.registerClass("UI_ServersManagerRetry",dofus["\r\x14"].gapi.ui.ServersManagerRetry);
      Object.registerClass("UI_Shortcuts",dofus["\r\x14"].gapi.ui.Shortcuts);
      Object.registerClass("UI_Debug",dofus["\r\x14"].gapi.ui.Debug);
      Object.registerClass("UI_Quests",dofus["\r\x14"].gapi.ui.Quests);
      Object.registerClass("UI_PartyItem",dofus["\r\x14"].gapi.ui["\x1e\x16\x1d"]["\x1e\x16\x1c"]);
      Object.registerClass("UI_Party",dofus["\r\x14"].gapi.ui.Party);
      Object.registerClass("UI_MountStorage",dofus["\r\x14"].gapi.ui.MountStorage);
      Object.registerClass("UI_BigStoreSell",dofus["\r\x14"].gapi.ui.BigStoreSell);
      Object.registerClass("UI_CrafterList",dofus["\r\x14"].gapi.ui.CrafterList);
      Object.registerClass("UI_BigStoreBuy",dofus["\r\x14"].gapi.ui.BigStoreBuy);
      Object.registerClass("UI_BigStoreBuy_DoubleFramerate",dofus["\r\x14"].gapi.ui.BigStoreBuy);
      Object.registerClass("UI_BigStoreSearch",dofus["\r\x14"].gapi.ui.BigStoreSearch);
      Object.registerClass("UI_BigStoreSearchFullSoul",dofus["\r\x14"].gapi.ui.BigStoreSearchFullSoul);
      Object.registerClass("UI_InventorySearch",dofus["\r\x14"].gapi.ui.InventorySearch);
      Object.registerClass("UI_QuestsObjectivetItem",dofus["\r\x14"].gapi.ui.quests["\x1e\x15\x16"]);
      Object.registerClass("UI_QuestsStepItem",dofus["\r\x14"].gapi.ui.quests["\x1e\x15\x14"]);
      Object.registerClass("UI_QuestsQuestItem",dofus["\r\x14"].gapi.ui.quests["\x1e\x15\x15"]);
      Object.registerClass("QuestStepViewer",dofus["\r\x14"].gapi.controls.QuestStepViewer);
      Object.registerClass("QuestStepListViewer",dofus["\r\x14"].gapi.controls.QuestStepListViewer);
      Object.registerClass("UI_PayZoneDialog",dofus["\r\x14"].gapi.ui.PayZoneDialog);
      Object.registerClass("UI_PayZoneDialog2",dofus["\r\x14"].gapi.ui.PayZoneDialog2);
      Object.registerClass("UI_PayZone",dofus["\r\x14"].gapi.ui.PayZone);
      Object.registerClass("UI_PayZone_DoubleFramerate",dofus["\r\x14"].gapi.ui.PayZone);
      Object.registerClass("UI_MovableContainerBar",dofus["\r\x14"].gapi.ui.MovableContainerBar);
      Object.registerClass("ButtonSubscribeUp",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("ButtonSubscribeDown",ank.gapi.controls.button.ButtonBackground);
      Object.registerClass("UI_LoginNewsItem",dofus["\r\x14"].gapi.ui.login["\x0b\x0b"]);
      Object.registerClass("UI_GiftsSprite",dofus["\r\x14"].gapi.ui.gifts["\r\x17"]);
      Object.registerClass("GAPIMain",dofus["\r\x14"].gapi["\r\x19"]);
      Object.registerClass("BATTLEFIELD",dofus["\r\x14"].battlefield["\x10\x18"]);
      Object.registerClass("ToolTip",ank.gapi.controls.ToolTip);
      Object.registerClass("ScrollBarThumb",ank.gapi.controls["\x1e\x13\x0b"]["\x1e\x13\n"]);
      Object.registerClass("ScrollBar",ank.gapi.controls.ScrollBar);
      Object.registerClass("PopupMenu",ank.gapi.controls.PopupMenu);
      Object.registerClass("Fps",ank.gapi.controls.Fps);
      Object.registerClass("ConsoleLogger",ank.gapi.controls.ConsoleLogger);
      Object.registerClass("Compass",ank.gapi.controls.Compass);
      Object.registerClass("Clock",ank.gapi.controls.Clock);
      Object.registerClass("MiniMap",dofus["\r\x14"].gapi.controls.MiniMap);
      Object.registerClass("SpriteViewer",dofus["\r\x14"].gapi.controls.SpriteViewer);
      Object.registerClass("UI_AutomaticServer",dofus["\r\x14"].gapi.ui.AutomaticServer);
      Object.registerClass("UI_AutomaticServer_DoubleFramerate",dofus["\r\x14"].gapi.ui.AutomaticServer);
      Object.registerClass("UI_ServerInformations",dofus["\r\x14"].gapi.ui.ServerInformations);
      Object.registerClass("UI_TitleDisplayer",dofus["\r\x14"].gapi.ui.TitleDisplayer);
      Object.registerClass("UI_ForgemagusCraft",dofus["\r\x14"].gapi.ui.ForgemagusCraft);
      Object.registerClass("UI_KnownledgeBase",dofus["\r\x14"].gapi.ui.KnownledgeBase);
      Object.registerClass("UI_KnownledgeBaseCategory",dofus["\r\x14"].gapi.ui["\f\x02"].KnownledgeBaseCategoryItem);
      Object.registerClass("UI_KnownledgeBaseItem",dofus["\r\x14"].gapi.ui["\f\x02"]["\f\x01"]);
      Object.registerClass("Helper",dofus["\r\x14"].gapi.controls.Helper);
      Object.registerClass("Helper_DoubleFramerate",dofus["\r\x14"].gapi.controls.Helper);
      Object.registerClass("UI_FloatingTips",dofus["\r\x14"].gapi.ui.FloatingTips);
      Object.registerClass("MouseShortcuts",dofus["\r\x14"].gapi.controls.MouseShortcuts);
      Object.registerClass("ColorSelector",dofus["\r\x14"].gapi.controls.ColorSelector);
      Object.registerClass("UI_SpellViewerOnCreate",dofus["\r\x14"].gapi.ui.SpellViewerOnCreate);
      Object.registerClass("UI_HistoryViewerOnCreate",dofus["\r\x14"].gapi.ui.HistoryViewerOnCreate);
      Object.registerClass("ClassSelector",dofus["\r\x14"].gapi.controls.ClassSelector);
      Object.registerClass("UI_GuildHouseRights",dofus["\r\x14"].gapi.ui.GuildHouseRights);
      Object.registerClass("GuildHousesViewer",dofus["\r\x14"].gapi.controls.GuildHousesViewer);
      Object.registerClass("GuildHousesViewerHouses",dofus["\r\x14"].gapi.controls["\r\x10"].GuildHousesViewerHouses);
      Object.registerClass("UI_ItemSummoner",dofus["\r\x14"].gapi.ui.ItemSummoner);
      Object.registerClass("UI_AskReportMessage",dofus["\r\x14"].gapi.ui.AskReportMessage);
      Object.registerClass("UI_Conquest",dofus["\r\x14"].gapi.ui.Conquest);
      Object.registerClass("ConquestStatsViewer",dofus["\r\x14"].gapi.controls.ConquestStatsViewer);
      Object.registerClass("ConquestZonesViewer",dofus["\r\x14"].gapi.controls.ConquestZonesViewer);
      Object.registerClass("ConquestJoinViewer",dofus["\r\x14"].gapi.controls.ConquestJoinViewer);
      Object.registerClass("UI_SpellForget",dofus["\r\x14"].gapi.ui.SpellForget);
      Object.registerClass("UI_SpellForgetItem",dofus["\r\x14"].gapi.ui["\x1e\x0e\x1b"]["\x1e\x0e\x1a"]);
      Object.registerClass("UI_ItemFound",dofus["\r\x14"].gapi.ui.ItemFound);
      Object.registerClass("UI_ChooseFeed",dofus["\r\x14"].gapi.ui.ChooseFeed);
      Object.registerClass("ConquestStatsViewerItem",dofus["\r\x14"].gapi.controls["\x12\n"].ConquestStatsViewerItem);
      Object.registerClass("StarsDisplayer",dofus["\r\x14"].gapi.controls.StarsDisplayer);
      Object.registerClass("ConquestZonesViewerAreaItem",dofus["\r\x14"].gapi.controls["\x12\x06"].ConquestZonesViewerAreaItem);
      Object.registerClass("ConquestZonesViewerVillageItem",dofus["\r\x14"].gapi.controls["\x12\x06"].ConquestZonesViewerVillageItem);
      Object.registerClass("EffectIcon",dofus["\r\x14"].battlefield.EffectIcon);
   }
}
